export default Images = {
  PROFILE_PICTURE: require('../../assets/Icons/profile_picture.png'),
  COMPANY: require('../../assets/company.jpg'),
  LIKE: require('../../assets/Icons/Like.png'),
  LOGOS: {
    LOGO1: require('../../assets/Logos/logo1.jpg'),
    LOGO2: require('../../assets/Logos/logo2.jpg'),
    LOGO3: require('../../assets/Logos/logo3.jpg'),
    LOGO4: require('../../assets/Logos/logo4.jpg'),
    LOGO5: require('../../assets/Logos/logo5.jpg'),
    LOGO6: require('../../assets/Logos/logo6.jpg'),
    LOGO7: require('../../assets/Logos/logo7.jpg'),
    LOGO8: require('../../assets/Logos/logo8.jpg'),
    LOGO9: require('../../assets/Logos/logo9.png'),
    UNIVERSITY: require('../../assets/Logos/university.png')
  },
  USERS: {
    USER1: require('../../assets/users/user1.jpg'),
    USER2: require('../../assets/users/user2.jpg'),
    USER3: require('../../assets/users/user3.jpg'),
    USER4: require('../../assets/users/user4.jpg'),
    USER5: require('../../assets/users/user5.jpg'),
    USER6: require('../../assets/users/user6.jpg'),
    USER7: require('../../assets/users/user7.jpg'),
    USER8: require('../../assets/users/user8.jpg'),
    USER9: require('../../assets/users/user9.jpg'),
    USER10: require('../../assets/users/user10.jpg'),
    USER11: require('../../assets/users/user11.jpg'),
    USER12: require('../../assets/users/user12.jpg'),
    USER13: require('../../assets/users/user13.jpg'),
  },
  BANNERS: {
    BANNER1: require('../../assets/banners/banner1.jpg'),
    BANNER2: require('../../assets/banners/banner2.jpg'),
    BANNER3: require('../../assets/banners/banner3.jpg'),
    BANNER4: require('../../assets/banners/banner4.jpg'),
    BANNER5: require('../../assets/banners/banner5.jpg'),
    BANNER6: require('../../assets/banners/banner6.jpg'),
    BANNER7: require('../../assets/banners/banner7.jpg'),
    BANNER8: require('../../assets/banners/banner8.jpg'),
    BANNER9: require('../../assets/banners/banner9.jpg'),
    BANNER10: require('../../assets/banners/banner10.jpg'),
    BANNER11: require('../../assets/banners/banner11.jpg'),
    BANNER12: require('../../assets/banners/banner12.jpg'),
    BANNER13: require('../../assets/banners/banner13.jpg'),
  },
  POSTS: {
    POST1: require('../../assets/Posts/post1.jpeg'),
    POST2: require('../../assets/Posts/post2.jpeg'),
    POST3: require('../../assets/Posts/post3.jpeg'),
    POST4: require('../../assets/Posts/post4.jpeg'),
    POST5: require('../../assets/Posts/post5.jpeg'),
    POST6: require('../../assets/Posts/post6.jpeg'),
  }
}