export default Screens = {
  HOME_STACK: "HOME_STACK", 
  HOME: "HOME",
  JOB_STACK: "JOB_STACK",
  JOB: "JOB",
  NOTIFICATION_STACK: "NOTIFICATION_STACK",
  NOTIFICATION: "NOTIFICATION",
  NETWORK_STACK: "NETWORK_STACK", 
  NETWORK: "NETWORK",
  POST_STACK: "POST_STACK",
  POST: "POST",
  PROFILE: "PROFILE",
}